stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - data/raw.csv
      - params.yaml
    outs:
      - data/processed/train.csv
      - data/processed/test.csv

  train:
    cmd: python src/train.py
    deps:
      - data/processed/train.csv
      - src/train.py
      - params.yaml
    outs:
      - models/model.pkl

  test:
    cmd: python src/test.py
    deps:
      - models/model.pkl
      - data/processed/test.csv
      - src/test.py
      - params.yaml
    outs:
      - experiments/results.json:
          persist: true
    metrics:
      - metrics.json


plots:
  - experiments/results.json:
      x: n_estimators
      y: accuracy
      title: "Random Forest: Accuracy vs n_estimators"