dataset:
  source: csv
  raw_csv_path: data/raw.csv
  target_col: income

split:
  test_size: 0.2
  random_state: 42
  stratify: true


preprocess:
  replace_question_mark_as_nan: true
  numeric_imputer: median
  categorical_imputer: most_frequent
  scale_numeric: true
  one_hot_encode: true
  drop_first: false
  save_preprocessor: true


model:
  type: random_forest
  random_forest:
    params:
      n_estimators: 250
      max_depth: 10
      min_samples_split: 20
      min_samples_leaf: 5
      n_jobs: -1
      class_weight:


test:
  metrics:
    average: binary
    pos_label: 1
    include:
    - accuracy
    - precision
    - recall
    - f1
paths:
  raw: data/raw.csv
  processed_train: data/processed/train.csv
  processed_test: data/processed/test.csv
  model: models/model.pkl
  preprocessor: models/preprocessor.pkl
  results: experiments/results.json
